DATA  SEGMENT
VAL   DB 'a'
DATA  ENDS
CODE  SEGMENT
      ASSUME CS:CODE,DS:DATA
START:MOV AX,DATA
      MOV DS,AX
      MOV AL,VAL
      SUB AL,20H
      MOV AH,02H
      INT 21H
      MOV AH,4CH
      INT 21H
CODE ENDS
END START