DATA  SEGMENT
      A DW 12,34,6,3,45,43
      CNT EQU ($-A)/2
DATA  ENDS 
CODE  SEGMENT
      ASSUME CS:CODE,DS:DATA
START:MOV AX,DATA
      MOV DS,AX  
      MOV CX,CNT-1  
  LP1:XOR SI,SI 
	XOR DI,DI        
  LP2:MOV AX,A[SI]
	MOV BX,A[SI+2]
	CMP AX,BX
	JL LP3
	MOV A[SI],BX
	MOV A[SI+2],AX	
  LP3:ADD SI,2 
	INC DI 
	CMP DI,CX 
	JB LP2
	LOOP LP1 
      MOV AH,4CH
      INT 21H
CODE ENDS
END START