DATA  SEGMENT
      STR DB 'AB123CDEFGHIJKLMNOPQRSTUVWXYZ1234ABCDEFGHIJKLMNOPQRSTUVWXYZ1234ABCDEFGHIJKLMNOPQRSTUVWXYZ1234ABCDEFG'
DATA  ENDS
CODE  SEGMENT
      ASSUME CS:CODE,DS:DATA
START:MOV AX,DATA
	  MOV DS,AX
	  MOV BX,OFFSET STR
	  MOV CX,100
   LP:MOV AL,[BX]
	  CMP AL,48
	  JB NO
	  CMP AL,57
	  JA NO
	  MOV CL,1
	  JMP EXIT
   NO:INC BX
	  LOOP LP
	  MOV CL,0
 EXIT:MOV AH,4CH
	  INT 21H
CODE ENDS
END START 