DATA  SEGMENT
      STR DB 20,20 DUP('$')
DATA  ENDS
CODE  SEGMENT
      ASSUME CS:CODE,DS:DATA
START:MOV AX,DATA
      MOV DS,AX
      MOV AH,10
      LEA DX,STR
      INT 21H
      MOV BYTE PTR STR+0,10
      MOV BYTE PTR STR+1,13
      MOV AH,9
      INT 21H
      MOV AH,4CH
      INT 21H
CODE ENDS
END START